# _quarto-html.yml
project:
  output-dir: outputs/html
  resources:
    - resources/images/ants.png

website:
  announcement:
    dismissable: false
    content: "![](resources/images/ants.png){.iasi-ants-image}"
    type: light
    position: above-navbar

format:
  html:
    include-in-header: resources/js/iasi.html
    theme:
      - cosmo
      - resources/css/iasi.scss
    toc: true
    number-sections: true

book:
  navbar:
    title: "Technical Guide"
    left:
      - text: "Introducción"
        href: chapters/01-intro/index.qmd
      - text: "Fundamentos"
        href: chapters/02-fundamentals/index.qmd
      - text: "Instalación"
        href: chapters/03-installation/index.qmd
      - text: "Arquitectura"
        href: chapters/04-architecture/index.qmd
      - text: "Desarrollo"
        href: chapters/05-development/index.qmd
      - text: "Next steps"
        href: chapters/06-next-steps/index.qmd
    right:
      - icon: file-pdf
        href: IASI-Quarto-Technical-Guide.pdf
        aria-label: "Descargar guía en PDF"
      - icon: translate
        href: https://iasi-org.github.io/iasi-home/pages/common/manifesto-bilingual.html
        aria-label: "Idioma / Language"
      - icon: envelope
        href: https://iasi-org.github.io/iasi-home/pages/common/contact.html
        aria-label: "Contacto"
